# goal
geometry_msgs/PoseStamped target_pose  # Objetivo de la acción, una posición y orientación

---
# result
bool success  # Indica si se alcanzó la posición
string message  # Un mensaje para describir el resultado final

---
# feedback
float32 progress  # Un valor que representa el progreso del movimiento, por ejemplo, un porcentaje
